Repository ml-research/liground, pull requests merged in 2021-01, with the labels that each got.

#37 Principal Variation Line Navigation - US_9
  src/renderer/components/AnalysisView.vue
  src/renderer/components/ChessGround.vue
  src/renderer/components/PVLines.vue
  src/renderer/store.js
Labels: enhancement

#67 Engine IPC - US_18
  .electron-vue/webpack.renderer.config.js
  .electron-vue/webpack.web.config.js
  .eslintrc.js
  .gitignore
  README.md
  package.json
  src/main/engine/driver.js
  src/main/engine/engines.js
  src/main/engine/index.js
  src/main/index.js
  src/renderer/components/AnalysisEvalRow.vue
  src/renderer/components/AnalysisHead.vue
  src/renderer/components/AnalysisView.vue
  src/renderer/components/ChessGround.vue
  src/renderer/components/EvalBar.vue
  src/renderer/components/LiveEval.vue
  src/renderer/components/PVLines.vue
  src/renderer/components/RoundedSwitch.vue
  src/renderer/ipc.js
  src/renderer/store.js
  src/server/index.js
  static/bin/.gitkeep
Labels: bug, enhancement

#61 Finished US_11 More work needs to be done once engine_ipc is finished
  src/renderer/components/AnalysisHead.vue
  src/renderer/components/EvalPlot.vue
  src/renderer/components/LiveEval.vue
  src/renderer/store.js
Labels: enhancement

#76 Prepare for first build
  .electron-vue/webpack.main.config.js
  .electron-vue/webpack.renderer.config.js
  .gitignore
  README.md
  electron-builder.json
  engines/.gitkeep
  package-lock.json
  package.json
  src/main/engine/engines.js
  src/main/index.dev.js
  src/renderer/store.js
Labels: bug, enhancement

#81 Fix loading PGN with different variant
  src/renderer/store.js
Labels: bug
