Repository ml-research/liground, pull requests merged in 2021-03, with the labels that each got.

#90 Us 8
  .gitignore
  src/renderer/components/AnalysisView.vue
  src/renderer/components/ChessGround.vue
  src/renderer/components/GameBoards.vue
  src/renderer/components/JumpButtons.vue
  src/renderer/components/MoveHistoryNode.vue
  src/renderer/components/PVLines.vue
  src/renderer/store.js
Labels: enhancement

#119 css enhancements
  src/main/index.js
  src/renderer/components/GameBoards.vue
  src/renderer/components/LandingPage.vue
  src/renderer/store.js
Labels: bug

#116 US 17 - Additional Engines
  package.json
  scripts/build.js
  scripts/dev-client.js
  scripts/dev-runner.js
  scripts/postinstall.js
  src/renderer/assets/images/engines/chess_engine.svg
  src/renderer/assets/images/engines/stockfish_blue.png
  src/renderer/assets/images/engines/stockfish_purple.png
  src/renderer/components/AnalysisEvalRow.vue
  src/renderer/components/AnalysisView.vue
  src/renderer/components/EngineConsole.vue
  src/renderer/components/LiveEval.vue
  src/renderer/engine/driver.js
  src/renderer/engine/engine.worker.js
  src/renderer/engine/engines.js
  src/renderer/store.js
  src/renderer/store/engines.js
  webpack/main.config.js
  webpack/renderer.config.js
  webpack/web.config.js
Labels: enhancement

#96 US_15
  src/renderer/components/AnalysisHead.vue
  src/renderer/components/BoardStyleSelector.vue
  src/renderer/components/EvalBar.vue
  src/renderer/components/MenuBar.vue
  src/renderer/components/PieceStyleSelector.vue
  src/renderer/store.js
Labels: enhancement

#128 Refactor Eval Bar
  src/renderer/components/EvalBar.vue
  src/renderer/components/GameBoards.vue
Labels: bug, enhancement

#123 US5 - Engine Settings
  src/renderer/components/AnalysisView.vue
  src/renderer/components/GameBoards.vue
  src/renderer/components/PVLines.vue
  src/renderer/components/SettingsTab.vue
  src/renderer/store.js
Labels: enhancement

#122 Finished US_23
  src/renderer/components/EvalPlot.vue
  src/renderer/components/EvalPlotButton.vue
  src/renderer/components/GameBoards.vue
  src/renderer/engine/driver.js
  src/renderer/engine/engine.worker.js
  src/renderer/engine/index.js
  src/renderer/store.js
Labels: enhancement

#138 Fix missing # for some alternative check mates
  src/renderer/components/MoveHistoryNode.vue
Labels: bug

#125 Preview images for piece & board style selectors
  src/renderer/components/BoardStyleSelector.vue
  src/renderer/components/PieceStyleSelector.vue
  src/renderer/store.js
Labels: enhancement

#156 Update Fairy-Stockfish engine name & fix postinstall on mac
  scripts/postinstall.js
  src/renderer/store/engines.js
Labels: bug

#158 US_22 second merge & engine options fix
  src/renderer/assets/images/engines/chess_engine.svg
  src/renderer/components/AnalysisEvalRow.vue
  src/renderer/components/EngineModal.vue
  src/renderer/components/EngineSelect.vue
  src/renderer/components/MenuBar.vue
  src/renderer/components/PVLines.vue
  src/renderer/components/SettingsTab.vue
  src/renderer/engine/engine.worker.js
  src/renderer/engine/index.js
  src/renderer/store.js
  src/renderer/store/engines.js
Labels: enhancement

#152 Plot Fixes
  package-lock.json
  src/renderer/components/EvalPlot.vue
  src/renderer/components/EvalPlotButton.vue
Labels: bug, enhancement

#160 Misc fixes
  scripts/postinstall.js
  src/renderer/components/ChessGround.vue
  src/renderer/components/EngineStats.vue
  src/renderer/components/GameBoards.vue
  src/renderer/store.js
  src/renderer/store/engines.js
Labels: bug
